  
version: '3'

services:
  minecraft:
    ports:
      - "25565:25565"
    volumes:
      - "/home/mc/docker/mc:/data"
    environment:
      EULA: "TRUE"
      MAX_MEMORY: 8G
      VIEW_DISTANCE: 10
      MAX_PLAYERS: 10
      CONSOLE: "false"
      VERSION: "1.14.4"
      TYPE: "FORGE"
      FORGEVERSION: "28.2.0"
    image: itzg/minecraft-server
    restart: always
