
[General]
	#Reset pitch to 0 when teleporting to normal elevators ?
	resetPitchNormal = false
	#Should elevators have the same color in order to teleport ?
	sameColor = false
	#Elevator range
	#Range: 3 ~ 256
	range = 256
	#Realign players to the center of elevator ?
	precisionTarget = true
	#Reset pitch to 0 when teleporting to directional elevators ?
	resetPitchDirectional = true
	#Can mobs spawn on elevators ?
	mobSpawn = false

